#/bin/bash

touch test_ms_parse_identify.cpp
touch test_ms_parse_word.cpp
touch test_ms_parse_blank.cpp
touch test_ms_parse_newline.cpp
touch test_ms_parse_variable.cpp
touch test_ms_parse_list_token.cpp
touch test_ms_parse_pipe.cpp
touch test_ms_parse_equals.cpp
touch test_ms_parse_single_quote.cpp
touch test_ms_parse_double_quote.cpp
touch test_ms_parse_redirection.cpp
touch test_ms_parse_left_parenthesis.cpp
touch test_ms_parse_right_parenthesis.cpp
