version: '3'

services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    init: true
    command: "cat"
    volumes:
      - vscode_server_volume:/home/minishell/.vscode-server

volumes:
  vscode_server_volume:
    driver: local
