name: deploy minishell test image container

on:
  push:
    paths:
      - '.github/workflows/deploy-image.yml'
      - 'docker/ubuntu/Dockerfile'
jobs:
  Deploy-to-Github-Packages:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/palmneko/minishell-ubuntu
      IMAGE_TAG: 22.04
    steps:
      - uses: actions/checkout@v4

      - name: Check files
        run: |
          ls
          test -f docker/ubuntu/Dockerfile
      - name: Build image
        run: |
          bash scripts/build_minishell-ubuntu.sh
      - name: Login to Github Packages Registry
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${GITHUB_REPOSITORY_OWNER} --password-stdin
      - name: Push by tagname
        run: |
          docker push "${IMAGE_NAME}:${IMAGE_TAG}"
      - name: Push by latest
        run: |
          docker image tag "${IMAGE_NAME}:${IMAGE_TAG}" "${IMAGE_NAME}"
          docker push "${IMAGE_NAME}"
