name: test minishell

on: ["push"]
jobs:
  Test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/palmneko/minishell-ubuntu:22.04
    env:
      IMAGE_NAME: ghcr.io/palmneko/minishell-ubuntu
      IMAGE_TAG: 22.04
    steps:
      - uses: actions/checkout@v4
      - name: Unit test # google test
        run: |
          make -f tests/googletest/Makefile
          tests/googletest/test.out
      - name: System test # pytest
        run: |
          pytest tests/pytest
