name: test minishell

on: ["push"]
jobs:

  Test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/palmneko/minishell-ubuntu:22.04
    steps:
      - name: env
        run: |
          cd "/home/appuser"
          whoami
          pwd
          ls
          ls /
      - name: Cloning
        run: |
          git init /tmp/workdirectory
          cd /tmp/workdirectory
          git remote add origin ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}
          git fetch --depth 1 --no-recurse-submodules origin ${GITHUB_REF_NAME}
          git checkout --progress --force -B ${GITHUB_REF_NAME} ${GITHUB_REF_NAME}
      - name: Unit test # google test
        run: |
          make -f tests/googletest/Makefile
          tests/googletest/test.out
      - name: System test # pytest
        run: |
          pytest tests/pytest
