name: test minishell

on: ["push"]
jobs:

  Test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/palmneko/minishell-ubuntu:22.04
    steps:
      - name: install git
        run: |
          apt install -y git
      - name: Check Environment
        run: |
          ls /
          which pytest
          which git
          which g++
          which gcc
      - uses: actions/checkout@v4
      - name: Unit test # google test
        run: |
          make -f tests/googletest/Makefile
          tests/googletest/test.out
      - name: System test # pytest
        run: |
          pytest tests/pytest
